### ISSUE TITLE
Paper review 

### ISSUE THREAD

**Issue by HMMalek** [SuperKogito/pydiogment#5]
Proposed modifications to the paper : 
- Page 1: Summary-line 6: "and most deformation..." -> "as most deformation..." (rather an explanation) 
- Page 1 : Summary-line 11: "the scipy..." -> "the Scipy..."
- Page 1 : Amplitude based augmentation.Add Fade-line 1: " and a fade-out effects..." -> "and fade-out effect..." / "and a fade-out effects..." 
- Page 2: Add Noise: move the entire equation on a separate line.
- Page 3-line 2: "a separating features..." -> "a separating feature..."
- Page 3: Conclusion-line 2: "These strategies aims.." -> "These strategies aim..."

**Comment by SuperKogito** [comment]
Just updated it, let me know if I missed something or if there are more improvements :))

**Comment by HMMalek** [comment]
Typo line 6 in the Summary: spectograms.
Adjective small, last line in Summary, can be removed.
